snapshot/picture/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'picture'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('picture/add/', views.PictureCreate.as_view(), name='collect-add'),
]

snapshot/snapshot/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('picture/', include('picture.urls')),

]

snapshot/picture/models.py
from django.db import models
from django.urls import reverse

class Collect(models.Model):

    def get_absolute_url(self):
        return reverse('picture:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + '-' + self.nick_name

    name = models.CharField(max_length=100)
    nick_name = models.CharField(max_length=100)
    about = models.CharField(max_length=1000)
    image = models.CharField(max_length=1000)
    caption = models.CharField(max_length=1000)
    description = models.CharField(max_length=3000)

snapshot/picture/views.py
from django.shortcuts import render
from django.template import loader
from django.views.generic.edit import CreateView
from .models import Collect
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'picture/index.html'

    def get_queryset(self):
     return Collect.objects.all()

class PictureCreate(CreateView):
    model = Collect
    fields = ['name', 'nick_name', 'about', 'image', 'caption', 'description']

class DetailView(generic.DetailView):
    model = Collect
    template_name = 'picture/detail.html'

snapshot/picture/templates/picture/collect_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "picture/style.css" %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="navbar-brand first" href="{% url 'picture:index' %}">SnapShot!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'picture:index' %}">Home <span class="sr-only">(current)</span></a>
   </ul>
    <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'picture:collect-add' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add your snapshot!!!
                        </a>
                    </li>

                </ul>
  </div>
  </nav>
    <div class="container-fluid">
   <div class="row">
      <div class="col-sm-12 col-md-7">
         <div class="panel panel-default">
            <div class="panel-body">

                    <form class="form-horizontal" action=" " method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'picture/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>


            </div>
         </div>
      </div>
   </div>
</div>
</body>
</html>

snapshot/picture/templates/picture/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "picture/style.css" %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="navbar-brand first" href="{% url 'picture:index' %}">SnapShot!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'picture:index' %}">Home <span class="sr-only">(current)</span></a>
   </ul>
    <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'picture:collect-add' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add your snapshot!!!
                        </a>
                    </li>

                </ul>
  </div>
  </nav>
<div>
    <h2> {{collect.caption}}</h2>
    <img src="{{collect.image}}">
    <p> {{collect.description}}</p>
    <br>
    <h3> Contributed by:</h3>
    <p style="font-family: cursive; color: white"> {{collect.name}}</p>
    <p> Nick_name: {{collect.nick_name}}</p>
    <p>About: {{collect.about}}</p>
</div>


</body>
</html>

snapshot/picture/templates/picture/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small ">{{field.errors}}</span>

        </div>
        <label class="control-label col-sm-2">{{field.label_tag}} </label>
        <div class="col-sm-10"> {{field}}</div>

    </div>
{% endfor %}

snapshot/picture/templates/picture/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "picture/style.css" %}">
    <title>Document</title>
</head>
<body style="background-image: linear-gradient(to left bottom, #50c60e, #8a8200, #7c460a, #481f1b, #000000);">
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="navbar-brand first" href="{% url 'picture:index' %}">SnapShot!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'picture:index' %}">Home <span class="sr-only">(current)</span></a>
   </ul>
    <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'picture:collect-add' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add your snapshot!!!
                        </a>
                    </li>

                </ul>
  </div>
  </nav>
  <br>
  <br>
   <div class="jumbotron jumbotron-fluid jumb">
    <div class="container">
    <h1 class="display-4">THE SNAPSHOT</h1>
    <p class="lead" style="font-family: cursive; color: blue;">Share your best memory with us. To add your snap, click on 'Add your snapshot' and make sure you enter a valid URL of image.</p>
    </div>
   </div>
   <br>

   <div class="  jumbotron jumbotron-fluid" name="fig" style="background:
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.15) 30%, rgba(255,255,255,.3) 32%, rgba(255,255,255,0) 33%) 0 0,
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.1) 11%, rgba(255,255,255,.3) 13%, rgba(255,255,255,0) 14%) 0 0,
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.2) 17%, rgba(255,255,255,.43) 19%, rgba(255,255,255,0) 20%) 0 110px,
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.2) 11%, rgba(255,255,255,.4) 13%, rgba(255,255,255,0) 14%) -130px -170px,
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.2) 11%, rgba(255,255,255,.4) 13%, rgba(255,255,255,0) 14%) 130px 370px,
radial-gradient(rgba(255,255,255,0) 0, rgba(255,255,255,.1) 11%, rgba(255,255,255,.2) 13%, rgba(255,255,255,0) 14%) 0 0,
linear-gradient(45deg, #343702 0%, #184500 20%, #187546 30%, #006782 40%, #0b1284 50%, #760ea1 60%, #83096e 70%, #840b2a 80%, #b13e12 90%, #e27412 100%);
background-size: 470px 470px, 970px 970px, 410px 410px, 610px 610px, 530px 530px, 730px 730px, 100% 100%;
background-color: #840b2a;">
   <div class="col-md-12 span-2">
  <h2>Popular Snaps!!</h2>
   <h4>Here are some snaps of different contributors, to have look on them click on the 'Caption'!</h4>

  </div>
</div>

<ul>
   {% for picture in object_list %}

   <div class="col-lg-3 col-md-4 col-sm-6 " >
      <div class = "thumbnail">
         <img src = "{{picture.image}}" height="500 px" width="600 px">
          <div class = "caption">
              <a href="{% url 'picture:detail' picture.id %}"> {{picture.caption}} </a>
          <p style="font-family: cursive; color: white;"> contributed by: {{picture.nick_name}} </p>


         </div>
      </div>


   </div>
    {% endfor %}

</body>
</html>